# Generated by Django 2.2 on 2019-05-17 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Surat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Ady', models.CharField(max_length=100)),
                ('surat', models.ImageField(upload_to='')),
            ],
        ),
    ]
