# Generated by Django 2.2 on 2019-05-17 03:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='surat',
            old_name='surat',
            new_name='image',
        ),
    ]
